{
 "title": "LeanAgileDevOps",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "appName", "label": "app", "query": "node" },
   {
    "name": "time_interval",
    "label": "time interval",
    "query": "30s,1m,2m,5m,10m,15m,30m,1h,3h,6h"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests ",
   "type": "stat",
   "description": "This is the total number of requests made\n",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{appName=~\"$appName\"}))"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx ",
   "type": "stat",
   "description": "This is the number of successful requests.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{status=~\"(1|2).*\", appName=~\"$appName\"}))"
    }
   ]
  },
  {
   "title": "HTTP 3xx",
   "type": "stat",
   "description": "This is the number of 3xx requests.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{status=~\"3.*\", appName=~\"$appName\"}))"
    }
   ]
  },
  {
   "title": "HTTP 4xx ",
   "type": "stat",
   "description": "This is the number of 4xx requests.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{status=~\"4.*\", appName=~\"$appName\"}))"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "stat",
   "description": "This is the number of 5xx requests.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{status=~\"5.*\", appName=~\"$appName\"}))"
    }
   ]
  },
  {
   "title": "HTTP Requests by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_http_requests_total", "legendFormat": "HTTP {{status}}" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "graph",
   "description": "The total number of HTTP requests made within' each period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_http_requests_total{appName=~\"$appName\"})",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "% Success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{status!~\"5.*\", appName=~\"node\"}) or on() vector(0))  / scalar(sum(node_http_requests_total{appName=~\"node\"})) * 100"
    }
   ]
  },
  {
   "title": "Requests per second [$time_interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_http_duration_seconds_count[$time_interval]) ",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum(node_http_requests_total{status=~\"5.*\", appName=~\"node\"}) or on() vector(0)) / scalar(sum(node_http_requests_total{appName=~\"node\"})) * 100"
    }
   ]
  },
  {
   "title": "HTTP Requests duration (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 2, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_http_duration_seconds{quantile=\"0.5\",appName=\"$appName\"}*1000",
     "legendFormat": "Quantile {{quantile}}"
    },
    {
     "expr": "node_http_duration_seconds{quantile=\"0.9\",appName=\"$appName\"}*1000",
     "legendFormat": "Quantile {{quantile}}"
    },
    {
     "expr": "node_http_duration_seconds{quantile=\"0.99\",appName=\"$appName\"}*1000",
     "legendFormat": "Quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "Average response time [$time_interval]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scalar( rate(node_http_duration_seconds_sum[$time_interval]) or on() vector(0) / rate(node_http_duration_seconds_count[$time_interval]) ) * 1000"
    }
   ]
  },
  {
   "title": "Eventloop Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{appName=~\"node\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Rate of CPU Time Spent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{appName=\"node\"}[5m])",
     "legendFormat": "cpu time"
    }
   ]
  }
 ]
}